services:
  movie-site:
    image: nginx:alpine
    container_name: movie-site
    restart: unless-stopped
    ports:
      - 8083:80
    volumes:
      - /home/kilpi/movie-site-assets:/usr/share/nginx/html